################################################################################
#                          Project Euler Problem 029                           #
#                     https://projecteuler.net/problem=029                     #
#                                                                              #
# Author:   Chris B.                                                           #
# Date:     November 05, 2020                                                  #
################################################################################

def prob_029(n=100):
    ''' Return distinct terms in sequence
        generated by a^b for 2<=a<=100 and 2<=b<=100'''
    unique_nums = set()
    for i in range(2,n+1):
        for j in range(2,n+1):
            unique_nums.add(i**j)
    return len(unique_nums)

prob_029()